### ISSUE TITLE
Evaluator is calling non-existent function on Player Registry

### ISSUE THREAD

**Issue by barretodavid** [starknet-edu/starknet-erc721#9]
On line 69 of `Evaluator.cairo` there's a call to `Iplayers_registry.has_validated_exercice` which has a typo on the word "exercise".

```py
@view
func has_validated_exercise{syscall_ptr : felt*, pedersen_ptr : HashBuiltin*, range_check_ptr}(
    account : felt, exercise_id : felt
) -> (has_validated_exercice : felt):
    ...
    # Checking if the user already validated this exercice
    let (has_current_user_validated_exercice) = Iplayers_registry.has_validated_exercice( # <-- TYPO
        contract_address=_players_registry,
        account=account,
        workshop=_workshop_id,
        exercise=exercise_id,
    )
    return (has_current_user_validated_exercice)
end
```

Assuming that this version of `Evaluator.cairo` is deployed on the address referenced by the README ([0x7a91f4c9dd01788188d624bfda6bc02ef2bf7b40813a29fe3c92d37444ee736](https://beta-goerli.voyager.online/contract/0x07a91f4c9dd01788188d624bfda6bc02ef2bf7b40813a29fe3c92d37444ee736)) the call will fail because the deployed smart contract for Player Registry ([0x07ce4546e155222b02c9e0d592fe4c482c11551065cd0f534fd9eac1f0ae9861](https://beta-goerli.voyager.online/contract/0x07ce4546e155222b02c9e0d592fe4c482c11551065cd0f534fd9eac1f0ae9861#readContract)) referenced by Evaluator has the right spelling `has_validated_exercise`.

![Screen Shot 2022-07-30 at 7 07 07 PM](https://user-images.githubusercontent.com/2279046/182003047-07c5af70-89e2-42e9-b4d1-1e0ebdffbd07.png)

The PR #6 fixes the spelling but after merging both the Evaluator and the Player Registry smart contracts will need to be redeployed and the README of the exercise updated with the new addresses

**Comment by 0xLucqs** [comment]
fixed #6
